/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeguimientoIndexRouteImport } from './routes/seguimiento.index'
import { Route as ProduccionIndexRouteImport } from './routes/produccion.index'
import { Route as PostventaIndexRouteImport } from './routes/postventa.index'
import { Route as ComprasIndexRouteImport } from './routes/compras.index'
import { Route as ComercialIndexRouteImport } from './routes/comercial.index'
import { Route as AdministrativaIndexRouteImport } from './routes/administrativa.index'
import { Route as SeguimientoListaRouteImport } from './routes/seguimiento.lista'
import { Route as SeguimientoIdRouteImport } from './routes/seguimiento.$id'
import { Route as ComprasSolicitudesRouteImport } from './routes/compras.solicitudes'
import { Route as ComprasOrdenesRouteImport } from './routes/compras.ordenes'
import { Route as ComprasInventarioRouteImport } from './routes/compras.inventario'
import { Route as AdministrativaTransporteRouteImport } from './routes/administrativa.transporte'
import { Route as AdministrativaPagosRouteImport } from './routes/administrativa.pagos'
import { Route as AdministrativaOrdenesProduccionRouteImport } from './routes/administrativa.ordenes-produccion'
import { Route as AdministrativaFacturasRouteImport } from './routes/administrativa.facturas'
import { Route as AdministrativaCostosRouteImport } from './routes/administrativa.costos'
import { Route as ProduccionOrdenesIndexRouteImport } from './routes/produccion.ordenes.index'
import { Route as PostventaGarantiasIndexRouteImport } from './routes/postventa.garantias.index'
import { Route as ComprasProveedoresIndexRouteImport } from './routes/compras.proveedores.index'
import { Route as ComercialProyectosIndexRouteImport } from './routes/comercial.proyectos.index'
import { Route as ComercialClientesIndexRouteImport } from './routes/comercial.clientes.index'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin.usuarios.index'
import { Route as ProduccionOrdenesIdRouteImport } from './routes/produccion.ordenes.$id'
import { Route as PostventaGarantiasNuevaRouteImport } from './routes/postventa.garantias.nueva'
import { Route as PostventaGarantiasIdRouteImport } from './routes/postventa.garantias.$id'
import { Route as ComprasProveedoresNuevoRouteImport } from './routes/compras.proveedores.nuevo'
import { Route as ComercialProyectosNuevoRouteImport } from './routes/comercial.proyectos.nuevo'
import { Route as ComercialProyectosIdRouteImport } from './routes/comercial.proyectos.$id'
import { Route as ComercialClientesNuevoRouteImport } from './routes/comercial.clientes.nuevo'
import { Route as ComercialClientesIdRouteImport } from './routes/comercial.clientes.$id'
import { Route as AdminUsuariosNuevoRouteImport } from './routes/admin.usuarios.nuevo'
import { Route as AdminUsuariosIdRouteImport } from './routes/admin.usuarios.$id'
import { Route as ComercialClientesIdEditarRouteImport } from './routes/comercial.clientes.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoIndexRoute = SeguimientoIndexRouteImport.update({
  id: '/seguimiento/',
  path: '/seguimiento/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionIndexRoute = ProduccionIndexRouteImport.update({
  id: '/produccion/',
  path: '/produccion/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostventaIndexRoute = PostventaIndexRouteImport.update({
  id: '/postventa/',
  path: '/postventa/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasIndexRoute = ComprasIndexRouteImport.update({
  id: '/compras/',
  path: '/compras/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialIndexRoute = ComercialIndexRouteImport.update({
  id: '/comercial/',
  path: '/comercial/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativaIndexRoute = AdministrativaIndexRouteImport.update({
  id: '/administrativa/',
  path: '/administrativa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoListaRoute = SeguimientoListaRouteImport.update({
  id: '/seguimiento/lista',
  path: '/seguimiento/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoIdRoute = SeguimientoIdRouteImport.update({
  id: '/seguimiento/$id',
  path: '/seguimiento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasSolicitudesRoute = ComprasSolicitudesRouteImport.update({
  id: '/compras/solicitudes',
  path: '/compras/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasOrdenesRoute = ComprasOrdenesRouteImport.update({
  id: '/compras/ordenes',
  path: '/compras/ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasInventarioRoute = ComprasInventarioRouteImport.update({
  id: '/compras/inventario',
  path: '/compras/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativaTransporteRoute =
  AdministrativaTransporteRouteImport.update({
    id: '/administrativa/transporte',
    path: '/administrativa/transporte',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrativaPagosRoute = AdministrativaPagosRouteImport.update({
  id: '/administrativa/pagos',
  path: '/administrativa/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativaOrdenesProduccionRoute =
  AdministrativaOrdenesProduccionRouteImport.update({
    id: '/administrativa/ordenes-produccion',
    path: '/administrativa/ordenes-produccion',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdministrativaFacturasRoute = AdministrativaFacturasRouteImport.update({
  id: '/administrativa/facturas',
  path: '/administrativa/facturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativaCostosRoute = AdministrativaCostosRouteImport.update({
  id: '/administrativa/costos',
  path: '/administrativa/costos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionOrdenesIndexRoute = ProduccionOrdenesIndexRouteImport.update({
  id: '/produccion/ordenes/',
  path: '/produccion/ordenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostventaGarantiasIndexRoute = PostventaGarantiasIndexRouteImport.update({
  id: '/postventa/garantias/',
  path: '/postventa/garantias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasProveedoresIndexRoute = ComprasProveedoresIndexRouteImport.update({
  id: '/compras/proveedores/',
  path: '/compras/proveedores/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProyectosIndexRoute = ComercialProyectosIndexRouteImport.update({
  id: '/comercial/proyectos/',
  path: '/comercial/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialClientesIndexRoute = ComercialClientesIndexRouteImport.update({
  id: '/comercial/clientes/',
  path: '/comercial/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/admin/usuarios/',
  path: '/admin/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionOrdenesIdRoute = ProduccionOrdenesIdRouteImport.update({
  id: '/produccion/ordenes/$id',
  path: '/produccion/ordenes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostventaGarantiasNuevaRoute = PostventaGarantiasNuevaRouteImport.update({
  id: '/postventa/garantias/nueva',
  path: '/postventa/garantias/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const PostventaGarantiasIdRoute = PostventaGarantiasIdRouteImport.update({
  id: '/postventa/garantias/$id',
  path: '/postventa/garantias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasProveedoresNuevoRoute = ComprasProveedoresNuevoRouteImport.update({
  id: '/compras/proveedores/nuevo',
  path: '/compras/proveedores/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProyectosNuevoRoute = ComercialProyectosNuevoRouteImport.update({
  id: '/comercial/proyectos/nuevo',
  path: '/comercial/proyectos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialProyectosIdRoute = ComercialProyectosIdRouteImport.update({
  id: '/comercial/proyectos/$id',
  path: '/comercial/proyectos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialClientesNuevoRoute = ComercialClientesNuevoRouteImport.update({
  id: '/comercial/clientes/nuevo',
  path: '/comercial/clientes/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialClientesIdRoute = ComercialClientesIdRouteImport.update({
  id: '/comercial/clientes/$id',
  path: '/comercial/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosNuevoRoute = AdminUsuariosNuevoRouteImport.update({
  id: '/admin/usuarios/nuevo',
  path: '/admin/usuarios/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosIdRoute = AdminUsuariosIdRouteImport.update({
  id: '/admin/usuarios/$id',
  path: '/admin/usuarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialClientesIdEditarRoute =
  ComercialClientesIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => ComercialClientesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administrativa/costos': typeof AdministrativaCostosRoute
  '/administrativa/facturas': typeof AdministrativaFacturasRoute
  '/administrativa/ordenes-produccion': typeof AdministrativaOrdenesProduccionRoute
  '/administrativa/pagos': typeof AdministrativaPagosRoute
  '/administrativa/transporte': typeof AdministrativaTransporteRoute
  '/compras/inventario': typeof ComprasInventarioRoute
  '/compras/ordenes': typeof ComprasOrdenesRoute
  '/compras/solicitudes': typeof ComprasSolicitudesRoute
  '/seguimiento/$id': typeof SeguimientoIdRoute
  '/seguimiento/lista': typeof SeguimientoListaRoute
  '/administrativa/': typeof AdministrativaIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/postventa/': typeof PostventaIndexRoute
  '/produccion/': typeof ProduccionIndexRoute
  '/seguimiento/': typeof SeguimientoIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/nuevo': typeof AdminUsuariosNuevoRoute
  '/comercial/clientes/$id': typeof ComercialClientesIdRouteWithChildren
  '/comercial/clientes/nuevo': typeof ComercialClientesNuevoRoute
  '/comercial/proyectos/$id': typeof ComercialProyectosIdRoute
  '/comercial/proyectos/nuevo': typeof ComercialProyectosNuevoRoute
  '/compras/proveedores/nuevo': typeof ComprasProveedoresNuevoRoute
  '/postventa/garantias/$id': typeof PostventaGarantiasIdRoute
  '/postventa/garantias/nueva': typeof PostventaGarantiasNuevaRoute
  '/produccion/ordenes/$id': typeof ProduccionOrdenesIdRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/comercial/clientes/': typeof ComercialClientesIndexRoute
  '/comercial/proyectos/': typeof ComercialProyectosIndexRoute
  '/compras/proveedores/': typeof ComprasProveedoresIndexRoute
  '/postventa/garantias/': typeof PostventaGarantiasIndexRoute
  '/produccion/ordenes/': typeof ProduccionOrdenesIndexRoute
  '/comercial/clientes/$id/editar': typeof ComercialClientesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administrativa/costos': typeof AdministrativaCostosRoute
  '/administrativa/facturas': typeof AdministrativaFacturasRoute
  '/administrativa/ordenes-produccion': typeof AdministrativaOrdenesProduccionRoute
  '/administrativa/pagos': typeof AdministrativaPagosRoute
  '/administrativa/transporte': typeof AdministrativaTransporteRoute
  '/compras/inventario': typeof ComprasInventarioRoute
  '/compras/ordenes': typeof ComprasOrdenesRoute
  '/compras/solicitudes': typeof ComprasSolicitudesRoute
  '/seguimiento/$id': typeof SeguimientoIdRoute
  '/seguimiento/lista': typeof SeguimientoListaRoute
  '/administrativa': typeof AdministrativaIndexRoute
  '/comercial': typeof ComercialIndexRoute
  '/compras': typeof ComprasIndexRoute
  '/postventa': typeof PostventaIndexRoute
  '/produccion': typeof ProduccionIndexRoute
  '/seguimiento': typeof SeguimientoIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/nuevo': typeof AdminUsuariosNuevoRoute
  '/comercial/clientes/$id': typeof ComercialClientesIdRouteWithChildren
  '/comercial/clientes/nuevo': typeof ComercialClientesNuevoRoute
  '/comercial/proyectos/$id': typeof ComercialProyectosIdRoute
  '/comercial/proyectos/nuevo': typeof ComercialProyectosNuevoRoute
  '/compras/proveedores/nuevo': typeof ComprasProveedoresNuevoRoute
  '/postventa/garantias/$id': typeof PostventaGarantiasIdRoute
  '/postventa/garantias/nueva': typeof PostventaGarantiasNuevaRoute
  '/produccion/ordenes/$id': typeof ProduccionOrdenesIdRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
  '/comercial/clientes': typeof ComercialClientesIndexRoute
  '/comercial/proyectos': typeof ComercialProyectosIndexRoute
  '/compras/proveedores': typeof ComprasProveedoresIndexRoute
  '/postventa/garantias': typeof PostventaGarantiasIndexRoute
  '/produccion/ordenes': typeof ProduccionOrdenesIndexRoute
  '/comercial/clientes/$id/editar': typeof ComercialClientesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administrativa/costos': typeof AdministrativaCostosRoute
  '/administrativa/facturas': typeof AdministrativaFacturasRoute
  '/administrativa/ordenes-produccion': typeof AdministrativaOrdenesProduccionRoute
  '/administrativa/pagos': typeof AdministrativaPagosRoute
  '/administrativa/transporte': typeof AdministrativaTransporteRoute
  '/compras/inventario': typeof ComprasInventarioRoute
  '/compras/ordenes': typeof ComprasOrdenesRoute
  '/compras/solicitudes': typeof ComprasSolicitudesRoute
  '/seguimiento/$id': typeof SeguimientoIdRoute
  '/seguimiento/lista': typeof SeguimientoListaRoute
  '/administrativa/': typeof AdministrativaIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/compras/': typeof ComprasIndexRoute
  '/postventa/': typeof PostventaIndexRoute
  '/produccion/': typeof ProduccionIndexRoute
  '/seguimiento/': typeof SeguimientoIndexRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/admin/usuarios/nuevo': typeof AdminUsuariosNuevoRoute
  '/comercial/clientes/$id': typeof ComercialClientesIdRouteWithChildren
  '/comercial/clientes/nuevo': typeof ComercialClientesNuevoRoute
  '/comercial/proyectos/$id': typeof ComercialProyectosIdRoute
  '/comercial/proyectos/nuevo': typeof ComercialProyectosNuevoRoute
  '/compras/proveedores/nuevo': typeof ComprasProveedoresNuevoRoute
  '/postventa/garantias/$id': typeof PostventaGarantiasIdRoute
  '/postventa/garantias/nueva': typeof PostventaGarantiasNuevaRoute
  '/produccion/ordenes/$id': typeof ProduccionOrdenesIdRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/comercial/clientes/': typeof ComercialClientesIndexRoute
  '/comercial/proyectos/': typeof ComercialProyectosIndexRoute
  '/compras/proveedores/': typeof ComprasProveedoresIndexRoute
  '/postventa/garantias/': typeof PostventaGarantiasIndexRoute
  '/produccion/ordenes/': typeof ProduccionOrdenesIndexRoute
  '/comercial/clientes/$id/editar': typeof ComercialClientesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administrativa/costos'
    | '/administrativa/facturas'
    | '/administrativa/ordenes-produccion'
    | '/administrativa/pagos'
    | '/administrativa/transporte'
    | '/compras/inventario'
    | '/compras/ordenes'
    | '/compras/solicitudes'
    | '/seguimiento/$id'
    | '/seguimiento/lista'
    | '/administrativa/'
    | '/comercial/'
    | '/compras/'
    | '/postventa/'
    | '/produccion/'
    | '/seguimiento/'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/nuevo'
    | '/comercial/clientes/$id'
    | '/comercial/clientes/nuevo'
    | '/comercial/proyectos/$id'
    | '/comercial/proyectos/nuevo'
    | '/compras/proveedores/nuevo'
    | '/postventa/garantias/$id'
    | '/postventa/garantias/nueva'
    | '/produccion/ordenes/$id'
    | '/admin/usuarios/'
    | '/comercial/clientes/'
    | '/comercial/proyectos/'
    | '/compras/proveedores/'
    | '/postventa/garantias/'
    | '/produccion/ordenes/'
    | '/comercial/clientes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/administrativa/costos'
    | '/administrativa/facturas'
    | '/administrativa/ordenes-produccion'
    | '/administrativa/pagos'
    | '/administrativa/transporte'
    | '/compras/inventario'
    | '/compras/ordenes'
    | '/compras/solicitudes'
    | '/seguimiento/$id'
    | '/seguimiento/lista'
    | '/administrativa'
    | '/comercial'
    | '/compras'
    | '/postventa'
    | '/produccion'
    | '/seguimiento'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/nuevo'
    | '/comercial/clientes/$id'
    | '/comercial/clientes/nuevo'
    | '/comercial/proyectos/$id'
    | '/comercial/proyectos/nuevo'
    | '/compras/proveedores/nuevo'
    | '/postventa/garantias/$id'
    | '/postventa/garantias/nueva'
    | '/produccion/ordenes/$id'
    | '/admin/usuarios'
    | '/comercial/clientes'
    | '/comercial/proyectos'
    | '/compras/proveedores'
    | '/postventa/garantias'
    | '/produccion/ordenes'
    | '/comercial/clientes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/administrativa/costos'
    | '/administrativa/facturas'
    | '/administrativa/ordenes-produccion'
    | '/administrativa/pagos'
    | '/administrativa/transporte'
    | '/compras/inventario'
    | '/compras/ordenes'
    | '/compras/solicitudes'
    | '/seguimiento/$id'
    | '/seguimiento/lista'
    | '/administrativa/'
    | '/comercial/'
    | '/compras/'
    | '/postventa/'
    | '/produccion/'
    | '/seguimiento/'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/nuevo'
    | '/comercial/clientes/$id'
    | '/comercial/clientes/nuevo'
    | '/comercial/proyectos/$id'
    | '/comercial/proyectos/nuevo'
    | '/compras/proveedores/nuevo'
    | '/postventa/garantias/$id'
    | '/postventa/garantias/nueva'
    | '/produccion/ordenes/$id'
    | '/admin/usuarios/'
    | '/comercial/clientes/'
    | '/comercial/proyectos/'
    | '/compras/proveedores/'
    | '/postventa/garantias/'
    | '/produccion/ordenes/'
    | '/comercial/clientes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdministrativaCostosRoute: typeof AdministrativaCostosRoute
  AdministrativaFacturasRoute: typeof AdministrativaFacturasRoute
  AdministrativaOrdenesProduccionRoute: typeof AdministrativaOrdenesProduccionRoute
  AdministrativaPagosRoute: typeof AdministrativaPagosRoute
  AdministrativaTransporteRoute: typeof AdministrativaTransporteRoute
  ComprasInventarioRoute: typeof ComprasInventarioRoute
  ComprasOrdenesRoute: typeof ComprasOrdenesRoute
  ComprasSolicitudesRoute: typeof ComprasSolicitudesRoute
  SeguimientoIdRoute: typeof SeguimientoIdRoute
  SeguimientoListaRoute: typeof SeguimientoListaRoute
  AdministrativaIndexRoute: typeof AdministrativaIndexRoute
  ComercialIndexRoute: typeof ComercialIndexRoute
  ComprasIndexRoute: typeof ComprasIndexRoute
  PostventaIndexRoute: typeof PostventaIndexRoute
  ProduccionIndexRoute: typeof ProduccionIndexRoute
  SeguimientoIndexRoute: typeof SeguimientoIndexRoute
  AdminUsuariosIdRoute: typeof AdminUsuariosIdRoute
  AdminUsuariosNuevoRoute: typeof AdminUsuariosNuevoRoute
  ComercialClientesIdRoute: typeof ComercialClientesIdRouteWithChildren
  ComercialClientesNuevoRoute: typeof ComercialClientesNuevoRoute
  ComercialProyectosIdRoute: typeof ComercialProyectosIdRoute
  ComercialProyectosNuevoRoute: typeof ComercialProyectosNuevoRoute
  ComprasProveedoresNuevoRoute: typeof ComprasProveedoresNuevoRoute
  PostventaGarantiasIdRoute: typeof PostventaGarantiasIdRoute
  PostventaGarantiasNuevaRoute: typeof PostventaGarantiasNuevaRoute
  ProduccionOrdenesIdRoute: typeof ProduccionOrdenesIdRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
  ComercialClientesIndexRoute: typeof ComercialClientesIndexRoute
  ComercialProyectosIndexRoute: typeof ComercialProyectosIndexRoute
  ComprasProveedoresIndexRoute: typeof ComprasProveedoresIndexRoute
  PostventaGarantiasIndexRoute: typeof PostventaGarantiasIndexRoute
  ProduccionOrdenesIndexRoute: typeof ProduccionOrdenesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento/': {
      id: '/seguimiento/'
      path: '/seguimiento'
      fullPath: '/seguimiento/'
      preLoaderRoute: typeof SeguimientoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion/': {
      id: '/produccion/'
      path: '/produccion'
      fullPath: '/produccion/'
      preLoaderRoute: typeof ProduccionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postventa/': {
      id: '/postventa/'
      path: '/postventa'
      fullPath: '/postventa/'
      preLoaderRoute: typeof PostventaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/': {
      id: '/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof ComprasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/': {
      id: '/comercial/'
      path: '/comercial'
      fullPath: '/comercial/'
      preLoaderRoute: typeof ComercialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativa/': {
      id: '/administrativa/'
      path: '/administrativa'
      fullPath: '/administrativa/'
      preLoaderRoute: typeof AdministrativaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento/lista': {
      id: '/seguimiento/lista'
      path: '/seguimiento/lista'
      fullPath: '/seguimiento/lista'
      preLoaderRoute: typeof SeguimientoListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento/$id': {
      id: '/seguimiento/$id'
      path: '/seguimiento/$id'
      fullPath: '/seguimiento/$id'
      preLoaderRoute: typeof SeguimientoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/solicitudes': {
      id: '/compras/solicitudes'
      path: '/compras/solicitudes'
      fullPath: '/compras/solicitudes'
      preLoaderRoute: typeof ComprasSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/ordenes': {
      id: '/compras/ordenes'
      path: '/compras/ordenes'
      fullPath: '/compras/ordenes'
      preLoaderRoute: typeof ComprasOrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/inventario': {
      id: '/compras/inventario'
      path: '/compras/inventario'
      fullPath: '/compras/inventario'
      preLoaderRoute: typeof ComprasInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativa/transporte': {
      id: '/administrativa/transporte'
      path: '/administrativa/transporte'
      fullPath: '/administrativa/transporte'
      preLoaderRoute: typeof AdministrativaTransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativa/pagos': {
      id: '/administrativa/pagos'
      path: '/administrativa/pagos'
      fullPath: '/administrativa/pagos'
      preLoaderRoute: typeof AdministrativaPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativa/ordenes-produccion': {
      id: '/administrativa/ordenes-produccion'
      path: '/administrativa/ordenes-produccion'
      fullPath: '/administrativa/ordenes-produccion'
      preLoaderRoute: typeof AdministrativaOrdenesProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativa/facturas': {
      id: '/administrativa/facturas'
      path: '/administrativa/facturas'
      fullPath: '/administrativa/facturas'
      preLoaderRoute: typeof AdministrativaFacturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativa/costos': {
      id: '/administrativa/costos'
      path: '/administrativa/costos'
      fullPath: '/administrativa/costos'
      preLoaderRoute: typeof AdministrativaCostosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion/ordenes/': {
      id: '/produccion/ordenes/'
      path: '/produccion/ordenes'
      fullPath: '/produccion/ordenes/'
      preLoaderRoute: typeof ProduccionOrdenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postventa/garantias/': {
      id: '/postventa/garantias/'
      path: '/postventa/garantias'
      fullPath: '/postventa/garantias/'
      preLoaderRoute: typeof PostventaGarantiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/proveedores/': {
      id: '/compras/proveedores/'
      path: '/compras/proveedores'
      fullPath: '/compras/proveedores/'
      preLoaderRoute: typeof ComprasProveedoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/proyectos/': {
      id: '/comercial/proyectos/'
      path: '/comercial/proyectos'
      fullPath: '/comercial/proyectos/'
      preLoaderRoute: typeof ComercialProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/clientes/': {
      id: '/comercial/clientes/'
      path: '/comercial/clientes'
      fullPath: '/comercial/clientes/'
      preLoaderRoute: typeof ComercialClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion/ordenes/$id': {
      id: '/produccion/ordenes/$id'
      path: '/produccion/ordenes/$id'
      fullPath: '/produccion/ordenes/$id'
      preLoaderRoute: typeof ProduccionOrdenesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postventa/garantias/nueva': {
      id: '/postventa/garantias/nueva'
      path: '/postventa/garantias/nueva'
      fullPath: '/postventa/garantias/nueva'
      preLoaderRoute: typeof PostventaGarantiasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postventa/garantias/$id': {
      id: '/postventa/garantias/$id'
      path: '/postventa/garantias/$id'
      fullPath: '/postventa/garantias/$id'
      preLoaderRoute: typeof PostventaGarantiasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/proveedores/nuevo': {
      id: '/compras/proveedores/nuevo'
      path: '/compras/proveedores/nuevo'
      fullPath: '/compras/proveedores/nuevo'
      preLoaderRoute: typeof ComprasProveedoresNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/proyectos/nuevo': {
      id: '/comercial/proyectos/nuevo'
      path: '/comercial/proyectos/nuevo'
      fullPath: '/comercial/proyectos/nuevo'
      preLoaderRoute: typeof ComercialProyectosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/proyectos/$id': {
      id: '/comercial/proyectos/$id'
      path: '/comercial/proyectos/$id'
      fullPath: '/comercial/proyectos/$id'
      preLoaderRoute: typeof ComercialProyectosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/clientes/nuevo': {
      id: '/comercial/clientes/nuevo'
      path: '/comercial/clientes/nuevo'
      fullPath: '/comercial/clientes/nuevo'
      preLoaderRoute: typeof ComercialClientesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/clientes/$id': {
      id: '/comercial/clientes/$id'
      path: '/comercial/clientes/$id'
      fullPath: '/comercial/clientes/$id'
      preLoaderRoute: typeof ComercialClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/nuevo': {
      id: '/admin/usuarios/nuevo'
      path: '/admin/usuarios/nuevo'
      fullPath: '/admin/usuarios/nuevo'
      preLoaderRoute: typeof AdminUsuariosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/$id': {
      id: '/admin/usuarios/$id'
      path: '/admin/usuarios/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminUsuariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial/clientes/$id/editar': {
      id: '/comercial/clientes/$id/editar'
      path: '/editar'
      fullPath: '/comercial/clientes/$id/editar'
      preLoaderRoute: typeof ComercialClientesIdEditarRouteImport
      parentRoute: typeof ComercialClientesIdRoute
    }
  }
}

interface ComercialClientesIdRouteChildren {
  ComercialClientesIdEditarRoute: typeof ComercialClientesIdEditarRoute
}

const ComercialClientesIdRouteChildren: ComercialClientesIdRouteChildren = {
  ComercialClientesIdEditarRoute: ComercialClientesIdEditarRoute,
}

const ComercialClientesIdRouteWithChildren =
  ComercialClientesIdRoute._addFileChildren(ComercialClientesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdministrativaCostosRoute: AdministrativaCostosRoute,
  AdministrativaFacturasRoute: AdministrativaFacturasRoute,
  AdministrativaOrdenesProduccionRoute: AdministrativaOrdenesProduccionRoute,
  AdministrativaPagosRoute: AdministrativaPagosRoute,
  AdministrativaTransporteRoute: AdministrativaTransporteRoute,
  ComprasInventarioRoute: ComprasInventarioRoute,
  ComprasOrdenesRoute: ComprasOrdenesRoute,
  ComprasSolicitudesRoute: ComprasSolicitudesRoute,
  SeguimientoIdRoute: SeguimientoIdRoute,
  SeguimientoListaRoute: SeguimientoListaRoute,
  AdministrativaIndexRoute: AdministrativaIndexRoute,
  ComercialIndexRoute: ComercialIndexRoute,
  ComprasIndexRoute: ComprasIndexRoute,
  PostventaIndexRoute: PostventaIndexRoute,
  ProduccionIndexRoute: ProduccionIndexRoute,
  SeguimientoIndexRoute: SeguimientoIndexRoute,
  AdminUsuariosIdRoute: AdminUsuariosIdRoute,
  AdminUsuariosNuevoRoute: AdminUsuariosNuevoRoute,
  ComercialClientesIdRoute: ComercialClientesIdRouteWithChildren,
  ComercialClientesNuevoRoute: ComercialClientesNuevoRoute,
  ComercialProyectosIdRoute: ComercialProyectosIdRoute,
  ComercialProyectosNuevoRoute: ComercialProyectosNuevoRoute,
  ComprasProveedoresNuevoRoute: ComprasProveedoresNuevoRoute,
  PostventaGarantiasIdRoute: PostventaGarantiasIdRoute,
  PostventaGarantiasNuevaRoute: PostventaGarantiasNuevaRoute,
  ProduccionOrdenesIdRoute: ProduccionOrdenesIdRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
  ComercialClientesIndexRoute: ComercialClientesIndexRoute,
  ComercialProyectosIndexRoute: ComercialProyectosIndexRoute,
  ComprasProveedoresIndexRoute: ComprasProveedoresIndexRoute,
  PostventaGarantiasIndexRoute: PostventaGarantiasIndexRoute,
  ProduccionOrdenesIndexRoute: ProduccionOrdenesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
